### ISSUE TITLE
emacs front page does not display properly after updating to emacs 25

### ISSUE THREAD

**Issue by alexvong243f** [ahungry/color-theme-ahungry#3]
After updating to emacs 25,
the emacs front page becomes:
![emacs-broken-front-page](https://user-images.githubusercontent.com/10696787/27251813-a366b76e-533e-11e7-8977-5dc224455b69.png)

However, I find a workaround. Instead of having `(load-theme 'ahungry t)` in the `~/.emacs` file, we replace it with the following:
```
(add-hook 'focus-in-hook (lambda ()
                           (if (not (memq 'ahungry custom-enabled-themes))
                               (load-theme 'ahungry t))))
```

Now the emacs front page is pretty again:
![emacs-pretty-front-page](https://user-images.githubusercontent.com/10696787/27251876-1857460a-5340-11e7-8dc9-408554f31288.png)

**Comment by ahungry** [comment]
Thanks, I could add this to the README, but I'm not sure if I should auto-add to user hooks (since currently I don't auto-add the load-theme either).

**Comment by alexvong243f** [comment]
Matthew Carter <notifications@github.com> writes:

> Thanks, I could add this to the README, but I'm not sure if I should auto-add to user hooks (since
> currently I don't auto-add the load-theme either).
>
I think it is better not to auto-add to user hooks since they are
intended to be customized by users. What do you think?

**Comment by alexvong243f** [comment]
This is no longer a problem in Emacs 25.3, so I am closing this.
